### PR TITLE
Fix/replace deprecated q uery builder parameter setting

### PR DESCRIPTION
**Pull request by frwg**

### CODE REVIEW

**Comment by Phocacius** [comment]
No, the syntax within the sql query stays the same

**Comment by Phocacius** [comment]
only in the code when actually binding the parameter where it is already changed

**Comment by frwg** [comment]
@astroidex 

I just discovered that there is a more appropriate solution for this issue now.

just use

```
  featureType:
    [...]
    userColumn: user_name
  [...]
  filterUser: true
```
  
  This will save the user in the `userColumn` and will filter only those rows when loading ( in case you only want to save the user and not filter after it, you should try just dropping the `filterUser` entry)

**Comment by astroidex** [comment]
@frwg thanks for the answer.
Yes. I know about this possibility. Just wanted to ensure that the filter also works as before.

**Pull request merged**
