### PR TITLE
Feature/ensure ol7 compatibilty of draw donut

### PR DESCRIPTION
**Pull request by frwg**

### CODE REVIEW

**Comment by astroidex** [comment]
@frwg what was the problem when you draw a donut?

**Comment by frwg** [comment]
@astroidex it threw an Exeception, complaining that a constructor function was used without the 'new' operator (which worked in ol6)

**Comment by astroidex** [comment]
Tested. works fine

**Review by astroidex — APPROVED** [review]

**Comment by Phocacius** [comment]
yay, ES6 features coming to the core :partying_face:

**Review by Phocacius — APPROVED** [review]

**Comment by frwg** [comment]
> yay, ES6 features coming to the core 🥳

...finally

**Pull request merged**
