### PR TITLE
added translation mb.digitizer.toolset tooltips button

### PR DESCRIPTION
**Pull request by astroidex**
* Digitizer Buttons are not translated yet. Added translation for all possibilities.
* changed from yml style to full definition (like in en version)

### CODE REVIEW

**Comment by CharlyUnicorn** [comment]
@eSlider: can you review and merge this pull request?

**Comment by CharlyUnicorn** [comment]
@eSlider: can you review and merge this pull request?

**Comment by CharlyUnicorn** [comment]
@eSlider: can you review and merge this pull request?

**Comment by eSlider** [comment]
@CharlyUnicorn, please test with real application and give me an feedback, this it works, so I can merge it.

**Comment by eSlider** [comment]
@CharlyUnicorn, but before I can merge this, there is some conflicts, this should be resolved first.

**Pull request closed without merging**
